captainVersion: 4
services:
    # Uptime Kuma
    $$cap_appname:
        image: louislam/uptime-kuma:latest
        restart: unless-stopped
        volumes:
            - $$cap_appname-data:/app/data
        caproverExtra:
            containerHttpPort: '3001'
caproverOneClickApp:
    instructions:
        start: |-
            Features

            ◉ Monitoring uptime for HTTP(s) / TCP / Ping.
            ◉ Fancy, Reactive, Fast UI/UX.
            ◉ Notifications via Webhook, Telegram, Discord and email (SMTP).
            ◉ 20 seconds interval.
        end: |-
            Aaaand you're done! 😄
            Your service is available at http://$$cap_appname.$$cap_root_domain
    displayName: Uptime Kuma
    isOfficial: true
    description: A fancy self-hosted monitoring tool
    documentation: Taken from https://github.com/louislam/uptime-kuma
